nanocomputers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("web.urls"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "NANOCOMPUTERS Administration"
admin.site.site_title = "NANOCOMPUTERS Admin Portal"
admin.site.index_title = "Welcome to NANOCOMPUTERS Admin Portal"

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("blog", views.blog, name="blog"),
    path("blog-details/<int:id>/", views.blog_details, name="blog-details"),
    path("shop", views.shop, name="shop"),
    path("contact", views.contact, name="contact"),
    path("cart", views.cart, name="cart"),
    path("checkout", views.checkout, name="checkout"),
    path("checkout/<int:id>/", views.checkout, name="checkout"),
    path("single-product/<int:id>/", views.single_product, name="single-product"),
    path("single-product", views.single_product, name="single-product"),
    path("add-cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove-cart/<int:product_id>/", views.remove_cart, name="remove_cart"),
    path(
        "remove-cart-item/<int:product_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
]

templates/web/blog-details.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}

    <main class="main-wrapper">
        <!-- Start Blog Area  -->
        
        <div class="axil-blog-area axil-section-gap">
            <div class="axil-single-post post-formate post-standard">
                <div class="container">
                    <div class="content-block">
                        <div class="inner">
                            <div class="post-thumbnail">
                                <img src="{{blog.blog_image.crop.1110x521}}" alt="blog Images">
                            </div>
                            <!-- End .thumbnail -->
                        </div>
                    </div>
                    <!-- End .content-blog -->
                </div>
            </div>
            <!-- End .single-post -->
            <div class="post-single-wrapper position-relative">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-1">
                            
                        </div>
                        
                        <div class="col-lg-10 axil-post-wrapper">
                            <div class="post-heading">
                                <h2 class="title">{{blog.blog_title}}</h2>
                                <div class="axil-post-meta">
                                    <div class="post-author-avatar">
                                        <img src="{{blog.blogger_image.url}}" alt="Author Images">
                                    </div>
                                    <div class="post-meta-content">
                                        <h6 class="author-title">
                                            <a href="#">{{blog.blogger_name}}</a>
                                        </h6>
                                        <ul class="post-meta-list">
                                            <li>{{blog.blog_date}}</li>
                                            
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <p>{{blog.blog_content}}</p>

                            
                            

                            

                            

                            

                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
        
        <!-- End Blog Area  -->



        <!-- Start Axil Newsletter Area  -->
        <div class="axil-newsletter-area axil-section-gap pt--0">
            <div class="container">
                <div class="etrade-newsletter-wrapper bg_image bg_image--5">
                    <div class="newsletter-content">
                        <span class="title-highlighter highlighter-primary2"><i class="fas fa-envelope-open"></i>Newsletter</span>
                        <h2 class="title mb--40 mb_sm--30">Get weekly update</h2>
                        <div class="input-group newsletter-form">
                            <div class="position-relative newsletter-inner mb--15">
                                <input placeholder="example@gmail.com" type="text">
                            </div>
                            <button type="submit" class="axil-btn mb--15">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End .container -->
        </div>
        <!-- End Axil Newsletter Area  -->

    </main>


    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service1.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Fast &amp; Secure Delivery</h6>
                            <p>Tell about your service.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service2.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Money Back Guarantee</h6>
                            <p>Within 10 days.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service3.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">24 Hour Return Policy</h6>
                            <p>No question ask.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service4.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Pro Quality Support</h6>
                            <p>24/7 Live support.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/web/blog-grid.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}


    <main class="main-wrapper">
        <!-- Start Breadcrumb Area  -->
        <div class="axil-breadcrumb-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-8">
                        <div class="inner">
                            <ul class="axil-breadcrumb">
                                <li class="axil-breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                                <li class="separator"></li>
                                <li class="axil-breadcrumb-item active" aria-current="page">Blogs</li>
                            </ul>
                            <h1 class="title">Blog Grid</h1>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- End Breadcrumb Area  -->
        <!-- Start Blog Area  -->
        <div class="axil-blog-area axil-section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row g-5">
                            {% for blog in blog %}
                            <div class="col-md-4 col-6 col-sm-6">
                                <div class="content-blog blog-grid">
                                    <div class="inner">
                                        <div class="thumbnail">
                                            <a href="{% url 'web:blog-details' blog.id %}">
                                                <img src="{{blog.blog_image.crop.308x173}}" alt="Blog Images">
                                            </a>
                                            
                                        </div>
                                        <div class="content">
                                            <h5 class="title"><a href="{% url 'web:blog-details' blog.id %}">{{blog.blog_title}}</a></h5>

                                            <div class="read-more-btn">
                                                <a class="axil-btn right-icon" href="{% url 'web:blog-details' blog.id %}">Read More <i class="fal fa-long-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </div>
                        
                    </div>
                    
                </div>
                <!-- End post-pagination -->
            </div>
            <!-- End .container -->
        </div>
        <!-- End Blog Area  -->

        <!-- Start Axil Newsletter Area  -->
        <div class="axil-newsletter-area axil-section-gap pt--0">
            <div class="container">
                <div class="etrade-newsletter-wrapper bg_image bg_image--5">
                    <div class="newsletter-content">
                        <span class="title-highlighter highlighter-primary2"><i class="fas fa-envelope-open"></i>Newsletter</span>
                        <h2 class="title mb--40 mb_sm--30">Get weekly update</h2>
                        <div class="input-group newsletter-form">
                            <div class="position-relative newsletter-inner mb--15">
                                <input placeholder="example@gmail.com" type="text">
                            </div>
                            <button type="submit" class="axil-btn mb--15">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End .container -->
        </div>
        <!-- End Axil Newsletter Area  -->
    </main>

    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service1.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Fast &amp; Secure Delivery</h6>
                            <p>Tell about your service.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service2.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Money Back Guarantee</h6>
                            <p>Within 10 days.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service3.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">24 Hour Return Policy</h6>
                            <p>No question ask.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service4.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Pro Quality Support</h6>
                            <p>24/7 Live support.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
{% endblock %}

templates/web/cart.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}

    <main class="main-wrapper">

        <!-- Start Cart Area  -->
        <div class="axil-product-cart-area axil-section-gap">
            <div class="container">
                <div class="axil-product-cart-wrap">
                    <div class="product-table-heading">
                        <h4 class="title">Your Cart</h4>
                        
                    </div>
                    <div class="table-responsive">
                        <table class="table axil-product-table axil-cart-table mb--40">
                            <thead>
                                <tr>
                                    <th scope="col" class="product-remove"></th>
                                    <th scope="col" class="product-thumbnail">Product</th>
                                    <th scope="col" class="product-title"></th>
                                    <th scope="col" class="product-price">Price</th>
                                    <th scope="col" class="product-quantity">Quantity</th>
                                    <th scope="col" class="product-subtotal">Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in cart_items %}
                                <tr>
                                    <td class="product-remove"><a href="{% url 'web:remove_cart_item' cart_item.item.id %}" class="remove-wishlist"><i class="fal fa-times"></i></a></td>
                                    <td class="product-thumbnail"><a href="single-product.html"><img src="{{cart_item.item.product_image1.url}}" alt="Digital Product"></a></td>
                                    <td class="product-title"><a href="single-product.html">{{cart_item.item.product_name}}</a></td>
                                    <td class="product-price" data-title="Price"><span class="currency-symbol">Rs.</span>{{cart_item.item.product_price}}</td>
                                    <td class="product-quantity" data-title="">
                                        <a href="{% url 'web:add_cart' cart_item.item.id %}"><i class="fa fa-plus-circle" style="padding-left:25px;"></i></a>
                                                
                                            <input type="number" class="quantity-input" value="{{cart_item.quantity}}">
                                            
                                        <a href="{% url 'web:remove_cart' cart_item.item.id %}"><i class="fa fa-minus-circle" style="padding-left:25px;"></i></a>    
                                                           
                                    </td>
                                    <td class="product-subtotal" data-title="Subtotal"><span class="currency-symbol">Rs.</span>{{cart_item.sub_total}}</td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                    <div class="cart-update-btn-area">
                        
                        
                    </div>
                    <div class="row">
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6">
                            <div class="axil-order-summery order-checkout-summery">
                                <h5 class="title mb--20">Order Summary</h5>
                                <div class="summery-table-wrap">
                                    <table class="table summery-table">
                                        <thead>
                                            <tr>
                                                <th>Product</th>
                                                
                                                <th>Sub Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for cart_item in cart_items %}
                                            <tr class="order-product">
                                                
                                                <td>{{cart_item.item.product_name}} (Rs.{{cart_item.item.product_price}}) x {{cart_item.quantity}}<br/></td>
                                                 
                                                <td>Rs.{{cart_item.sub_total}}</td>                                             
                                                
                                            </tr>
                                            {% endfor %}
                                            
                                            
                                            <tr class="order-total">
                                                <td>Total</td>
                                                <td class="order-total-amount">{{total}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                
                                
                                <a href="{% url 'web:checkout' %}" class="axil-btn btn-bg-primary checkout-btn">Process to Checkout</a>
                                
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
        
        <!-- End Cart Area  -->

    </main>


    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service1.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Fast &amp; Secure Delivery</h6>
                            <p>Tell about your service.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service2.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Money Back Guarantee</h6>
                            <p>Within 10 days.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service3.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">24 Hour Return Policy</h6>
                            <p>No question ask.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service4.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Pro Quality Support</h6>
                            <p>24/7 Live support.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
{% endblock %}

templates/web/shop.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}

    <main class="main-wrapper">
        <!-- Start Breadcrumb Area  -->
        <div class="axil-breadcrumb-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-8">
                        <div class="inner">
                            <ul class="axil-breadcrumb">
                                <li class="axil-breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                                <li class="separator"></li>
                                <li class="axil-breadcrumb-item active" aria-current="page">Shop</li>
                            </ul>
                            <h1 class="title">Explore All Products</h1>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- End Breadcrumb Area  -->
        <!-- Start Shop Area  -->
        <div class="axil-shop-area axil-section-gap bg-color-white">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="axil-shop-top">
                            <div class="row">
                                <div class="col-lg-9">
                                    <div class="category-select">


                                        <!-- Start Single Select  -->
                                        <select class="single-select" onchange="location = this.value;">
                                            <option>Price Range</option>
                                            <option value="{% url 'web:shop' %}">All Products</option>
                                            {% for filter_price in filter_price %}
                                            <option value="shop?pricerange={{filter_price.id}}">{{filter_price.price_range}}</option>
                                            {% endfor %}
                                        </select>
                                        <!-- End Single Select  -->

                                        <!-- Start Single Select  -->
                                        <select class="single-select" onchange="location = this.value;">
                                            <option value="#">Sub Categories</option>
                                            <option value="{% url 'web:shop' %}">All Products</option>
                                            {% for subcategory in subcategory %}
                                            <option value="shop?subcategories={{subcategory.id}}">{{subcategory.sub_category_name}}</option>
                                            {% endfor %}
                                        </select>

                                        <!-- <ul>
                                            <li><a href="{% url 'web:shop' %}">All Products</a></li>
                                            {% for subcategory in subcategory %}
                                            <li><a href="shop?subcategories={{subcategory.id}}">{{subcategory.sub_category_name}}</a></li>
                                            {% endfor %}
                                        </ul> -->
                                        <!-- End Single Select  -->

                                        

                                        

                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row--15 pt--50 pt_sm--30">
                    {% for products in products %}
                    <div class="col-xl-3 col-lg-4 col-sm-6 col-6 mb--30">
                        <div class="axil-product product-style-one">
                            <div class="thumbnail">
                                <a href="{% url 'web:single-product' products.id %}">

                                    <img data-sal="zoom-out" data-sal-delay="200" data-sal-duration="800" loading="lazy" class="main-img" src="{{products.product_image1.crop.255x255}}" alt="Product Images">
                                    
                                </a>
                                <div class="label-block label-right">
                                    <div class="product-badget">{{products.product_off}}% Off</div>
                                </div>
                                <div class="product-hover-action">
                                    <ul class="cart-action">
                                        
                                        <li class="select-option">
                                            <a href="{% url 'web:single-product' products.id %}">
                                                Buy Now
                                            </a>
                                        </li>
                                        <li class="quickview"><a href="{% url 'web:add_cart' products.id  %}"><i class="fas fa-shopping-cart"></i></a></li>
                                        
                                    </ul>
                                </div>
                                
                            </div>
                            <div class="product-content">
                                <div class="inner">
                                    
                                    <h5 class="title"><a href="{% url 'web:single-product' products.id %}">{{products.product_name}}</a></h5>
                                    <div class="product-price-variant">
                                        <span class="price current-price">{{products.product_price}}Rs.</span>
                                        <span class="price old-price">{{products.product_old_price}}Rs.</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}                          
                </div>
                
            </div>
            <!-- End .container -->
        </div>
        <!-- End Shop Area  -->
        <!-- Start Axil Newsletter Area  -->
        <div class="axil-newsletter-area axil-section-gap pt--0">
            <div class="container">
                <div class="etrade-newsletter-wrapper bg_image bg_image--5">
                    <div class="newsletter-content">
                        <span class="title-highlighter highlighter-primary2"><i class="fas fa-envelope-open"></i>Newsletter</span>
                        <h2 class="title mb--40 mb_sm--30">Get weekly update</h2>
                        <div class="input-group newsletter-form">
                            <div class="position-relative newsletter-inner mb--15">
                                <input placeholder="example@gmail.com" type="text">
                            </div>
                            <button type="submit" class="axil-btn mb--15">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End .container -->
        </div>
        <!-- End Axil Newsletter Area  -->
    </main>


    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service1.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Fast &amp; Secure Delivery</h6>
                            <p>Tell about your service.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service2.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Money Back Guarantee</h6>
                            <p>Within 10 days.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service3.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">24 Hour Return Policy</h6>
                            <p>No question ask.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="{% static 'web/images/icons/service4.png' %}" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">Pro Quality Support</h6>
                            <p>24/7 Live support.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}