nanocomputers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("web.urls"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "NANOCOMPUTERS Administration"
admin.site.site_title = "NANOCOMPUTERS Admin Portal"
admin.site.index_title = "Welcome to NANOCOMPUTERS Admin Portal"

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("blog", views.blog, name="blog"),
    path("blog-details/<int:id>/", views.blog_details, name="blog-details"),
    path("shop", views.shop, name="shop"),
    path("contact", views.contact, name="contact"),
    path("cart", views.cart, name="cart"),
    path("checkout", views.checkout, name="checkout"),
    path("checkout/<int:id>/", views.checkout, name="checkout"),
    path("single-product/<int:id>/", views.single_product, name="single-product"),
    path("single-product", views.single_product, name="single-product"),
    path("add-cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove-cart/<int:product_id>/", views.remove_cart, name="remove_cart"),
    path(
        "remove-cart-item/<int:product_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
]

templates/web/partials/footer.html
{% load static %}
<!-- Start Footer Area  -->
<footer class="axil-footer-area footer-style-2">
    <!-- Start Footer Top Area  -->
    <div class="footer-top separator-top">
        <div class="container">
            <div class="row">
                <!-- Start Single Widget  -->
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="axil-footer-widget">
                        <h5 class="widget-title">Support</h5>
                        <!-- <div class="logo mb--30">
                        <a href="index.html">
                            <img class="light-logo" src="{% static 'web/images/logo/logo.png' %}" alt="Logo Images">
                        </a>
                    </div> -->
                        <div class="inner">
                            <p>2nd Floor Rajadani Building,<br>Opposite Surabhi mall,<br>Ramanattukara, Kerala
                            </p>
                            <ul class="support-list-item">
                                <li><a href="mailto:nanocomputersrk@gmail.com"><i class="fal fa-envelope-open"></i>nanocomputersrk@gmail.com</a></li>
                                <li><a href="tel:(+01)850-315-5862"><i class="fal fa-phone-alt"></i>077365 55535</a></li>
                                <!-- <li><i class="fal fa-map-marker-alt"></i> 685 Market Street,  <br> Las Vegas, LA 95820, <br> United States.</li> -->
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Widget  -->
                <!-- Start Single Widget  -->
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="axil-footer-widget">
                        <h5 class="widget-title">Account</h5>
                        <div class="inner">
                            <ul>
                                
                                <li><a href="{% url 'web:cart' %}">Cart</a></li>
                                <li><a href="{% url 'web:shop' %}">Shop</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Widget  -->
                <!-- Start Single Widget  -->
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="axil-footer-widget">
                        <h5 class="widget-title">Quick Link</h5>
                        <div class="inner">
                            <ul>
                                <li><a href="{% url 'web:about' %}">About</a></li>
                                <li><a href="{% url 'web:blog' %}">Blog</a></li>
                                <li><a href="{% url 'web:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Widget  -->
                <!-- Start Single Widget  -->
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="axil-footer-widget">
                        <h5 class="widget-title">Scan this QR</h5>
                        <div class="inner">
                            <!-- <span>Save $3 With App & New User only</span> -->
                            <div class="download-btn-group">
                                <div class="qr-code">
                                    <img src="{% static 'web/images/others/qr-code.png' %}" alt="Axilthemes">
                                </div>
                                <div class="app-link">
                                    <a href="#">
                                        <img src="{% static 'web/images/others/app-store.png' %}" alt="App Store">
                                    </a>
                                    <a href="#">
                                        <img src="{% static 'web/images/others/play-store.png' %}" alt="Play Store">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Single Widget  -->
            </div>
        </div>
    </div>
    <!-- End Footer Top Area  -->
    <!-- Start Copyright Area  -->
    <div class="copyright-area copyright-default separator-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-4">
                    <div class="social-share">
                        <a href="https://www.facebook.com/nanocomputers/"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/nanocomputersrk/"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a href="#"><i class="fab fa-discord"></i></a>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-12">
                    <div class="copyright-left d-flex flex-wrap justify-content-center">
                        <ul class="quick-link">
                            <li>© 2022. All rights reserved by <a target="_blank" href="https://gedexo.com/">Gedexo</a>.</li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-12">
                    <div class="copyright-right d-flex flex-wrap justify-content-xl-end justify-content-center align-items-center">
                        <span class="card-text">Accept For</span>
                        <ul class="payment-icons-bottom quick-link">
                            <li><img src="{% static 'web/images/icons/cart/cart-1.png' %}" alt="paypal cart"></li>
                            <li><img src="{% static 'web/images/icons/cart/cart-2.png' %}" alt="paypal cart"></li>
                            <li><img src="{% static 'web/images/icons/cart/cart-5.png' %}" alt="paypal cart"></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Copyright Area  -->
</footer>
<!-- End Footer Area  -->

templates/web/partials/header.html
{% load static %}
<body class="sticky-header newsletter-popup-modal">

    <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
<![endif]-->
    <a href="#top" class="back-to-top" id="backto-top"><i class="fal fa-arrow-up"></i></a>
    <header class="header axil-header header-style-1">
        
        <div class="axil-header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="header-top-dropdown">
                            
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="header-top-link">
                            <ul class="quick-link">
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Start Mainmenu Area  -->
        <div id="axil-sticky-placeholder"></div>
        <div class="axil-mainmenu">
            <div class="container">
                <div class="header-navbar">
                    <div class="header-brand">
                        <a href="{% url 'web:index' %}" class="logo logo-dark">
                            <img src="{% static 'web/images/logo/nano-logo.png' %}" alt="Site Logo">
                        </a>
                        
                    </div>
                    <div class="header-main-nav">
                        <!-- Start Mainmanu Nav -->
                        <nav class="mainmenu-nav">
                            <button class="mobile-close-btn mobile-nav-toggler"><i class="fas fa-times"></i></button>
                            <div class="mobile-nav-brand">
                                <a href="{% url 'web:index' %}" class="logo">
                                    <img src="{% static 'web/images/logo/nano-logo.png' %}" alt="Site Logo">
                                </a>
                            </div>
                            <ul class="mainmenu">
                                <li>
                                    <a href="{% url 'web:index' %}">Home</a>
                                </li>

                                <li>
                                    <a href="{% url 'web:shop' %}">Shop</a>                                   
                                </li>
                                <li><a href="{% url 'web:about' %}">About</a></li>
                                
                                
                                <li>
                                    <a href="{% url 'web:blog' %}">Blog</a>
                                    
                                </li>
                                <li><a href="{% url 'web:contact' %}">Contact</a></li>
                            </ul>
                        </nav>
                        <!-- End Mainmanu Nav -->
                    </div>
                    <div class="header-action">
                        <ul class="action-list">
                            
                            
                            <li class="shopping-cart">
                                <a href="{% url 'web:cart' %}" class="cart-dropdown-btn">
                                    <span class=""></span>
                                    <i class="flaticon-shopping-cart"></i>
                                </a>
                            </li>
                            
                            <li class="axil-mobile-toggle">
                                <button class="menu-btn mobile-nav-toggler">
                                    <i class="flaticon-menu-2"></i>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Mainmenu Area -->
    </header>